### PR TITLE
Tradução incial.

### PR DESCRIPTION
**Pull request by lucasplcorrea**
```release-note
pt-BR: Adiciona a tradução dos scripts de instalação para português do Brasil, visando globalizar o 1Panel e facilitar seu uso em ambientes de língua portuguesa.
Adds translation of installation scripts to Brazilian Portuguese, aiming to globalize 1Panel and facilitate its use in Portuguese-speaking environments.
```

English Version:
The installation version in pt-BR was created.

No commands were changed.
Only the comments were translated in order to maintain the originality of the installed version.

Check the possibility of creating a multi-language installer where, before starting the installation, a question is asked to the user in which language they want to install 1Panel.

I humbly made this translation in order to help other colleagues to install 1Panel more easily, a project that has helped me in my day to day life. Let's make this project global and reach all languages.

Portuguese Version:
Criada  a versão de instalação em pt-BR.

Nenhum comando foi alterado.
Realizado traduções apenas dos comentários com o intuito de manter a originalidade do instalado.

Verificar a possibilidade de criar um instalador multi-idioma onde antes de iniciar a instalação seja realizada uma pergunta questionando ao usuário em qual idioma ele pretende realizar a instalação do 1Panel.

Humildemente fiz essa tradução com o intuito de ajudar outros colegas a instalar com maior facilidade o 1Panel, projeto esse que vem me ajudado no dia a dia. Vamos fazer com que esse projeto seja global, e chegue a todas os idiomas.

### CODE REVIEW

**Comment by lucasplcorrea** [comment]
```release-note
pt-BR: Adiciona a tradução dos scripts de instalação para português do Brasil, visando globalizar o 1Panel e facilitar seu uso em ambientes de língua portuguesa.

en-US: Adds translation of installation scripts to Brazilian Portuguese, aiming to globalize 1Panel and facilitate its use in Portuguese-speaking environments.
```

**Comment by lucasplcorrea** [comment]
Hello @wanghe-fit2cloud, could you review this PR? I translated the installation scripts into Portuguese, seeking to globalize the project.

**Comment by wanghe-fit2cloud** [comment]
> Hello @wanghe-fit2cloud, could you review this PR? I translated the installation scripts into Portuguese, seeking to globalize the project.

Thank you for supporting our project! I will be making unified adjustments to the installer project soon to support internationalization during the 1Panel system installation process.
Once this work is complete, I kindly ask for your assistance in maintaining your language pack based on the new framework. Thank you so much!

**Comment by lucasplcorrea** [comment]
> > Hello @wanghe-fit2cloud, could you review this PR? I translated the installation scripts into Portuguese, seeking to globalize the project.
> 
> Thank you for supporting our project! I will be making unified adjustments to the installer project soon to support internationalization during the 1Panel system installation process. Once this work is complete, I kindly ask for your assistance in maintaining your language pack based on the new framework. Thank you so much!

it will be a pleasure to contribute to the project that has helped me every day.

I think that if in the future there is a possibility of creating a Brazilian translation package for 1panel, I could help too.

I tested my translated version, and it has worked perfectly, as quick_start.sh searches the github repository, I usually comment out the last line and make the replacements of the installation files after downloading, but if there was an option in quick_start.sh to select the preferred language, it would be excellent, because from that option the installer could download/load the correct files.

**Comment by wanghe-fit2cloud** [comment]
I have just submitted an updated version of the internationalization code with improvements. You can adapt it based on the latest code in the main branch.
Simply define the desired language in the quick_start.sh and install.sh scripts, and create the corresponding language file in the lang directory.
Looking forward to your contributions!

**Comment by lucasplcorrea** [comment]
Hey @wanghe-fit2cloud I made a new PR using the new version of your installer.

https://github.com/1Panel-dev/installer/pull/25

I'll close this one.

**Pull request closed without merging**
